apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "opta-agent.fullname" . }}
  labels:
  {{- include "opta-agent.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - extensions
      - apps
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - extensions
      - batch
    resources:
      - cronjobs
      - jobs
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - endpoints
      - services
      - replicationcontrollers
      - namespaces
    verbs:
      - list
      - get
      - watch