apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opta-agent.fullname" . }}
  labels:
    {{- include "opta-agent.labels" . | nindent 4 }}
  namespace: {{ include "opta-agent.namespaceName" . }}
spec:
  replicas: 1 # TODO: figure out HA by fixing kopf: https://kopf.readthedocs.io/en/latest/deployment/
  strategy:
    type: Recreate
  selector:
    matchLabels:
  {{- include "opta-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "opta-agent.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "opta-agent.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.optaAgent.image }}"
          imagePullPolicy: Always
          ports:
            - name: main
              protocol: TCP
              containerPort: 8080
          env:
            - name: OPTA_TOKEN
              valueFrom:
                secretKeyRef:
                  name: opta-secrets
                  key: token
          {{/* No probes for grpc at the moment */}}
          livenessProbe:
            initialDelaySeconds: 30
            httpGet:
              path: /healthz
              port: 8080
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 10
            httpGet:
              path: /healthz
              port: 8080
          resources:
            limits:
            {{- toYaml .Values.optaAgent.containerResourceLimits | nindent 14 }}
            requests:
      {{- toYaml .Values.optaAgent.containerResourceRequests | nindent 14 }}
