apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ include "opta-agent.namespaceName" . }}
  name:  {{ include "opta-agent.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name:  {{ include "opta-agent.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "opta-agent.fullname" . }}