apiVersion: v1
kind: Secret
metadata:
  namespace: {{ include "opta-agent.namespaceName" . }}
  name: opta-secrets
  labels:
  {{- include "opta-agent.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ default "MISSING" .Values.optaAgent.token | b64enc | quote }}