apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opta-agent.fullname" . }}
  labels:
  {{- include "opta-agent.labels" . | nindent 4 }}
  namespace: {{ include "opta-agent.namespaceName" . }}