apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ include "opta-agent.namespaceName" . }}
  name:  {{ include "opta-agent.fullname" . }}
rules:
  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [""]
    resources: [events]
    verbs: [create]
